# Generated by Django 4.0.3 on 2022-04-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='startUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('contactNo', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('iitian', models.BooleanField(default=False)),
                ('hostel', models.CharField(choices=[('1', 'HOSTEL 1'), ('2', 'HOSTEL 2'), ('3', 'HOSTEL 3'), ('4', 'HOSTEL 4'), ('5', 'HOSTEL 5'), ('6', 'HOSTEL 6'), ('7', 'HOSTEL 7'), ('8', 'HOSTEL 8'), ('9', 'HOSTEL 9')], default='1', max_length=9)),
                ('startup_name', models.CharField(max_length=30)),
                ('startup_sector', models.CharField(max_length=30)),
            ],
        ),
    ]
