# Generated by Django 4.0.3 on 2022-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='comments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_desc',
            field=models.CharField(default='description', max_length=1000),
        ),
    ]
