# Generated by Django 4.0.3 on 2022-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_startup_comments_startup_startup_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='hostel',
            field=models.CharField(choices=[('1', 'HOSTEL 1'), ('2', 'HOSTEL 2'), ('3', 'HOSTEL 3'), ('4', 'HOSTEL 4'), ('5', 'HOSTEL 5'), ('6', 'HOSTEL 6'), ('7', 'HOSTEL 7'), ('8', 'HOSTEL 8'), ('9', 'HOSTEL 9')], max_length=9),
        ),
    ]
