# Generated by Django 4.0.3 on 2022-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_startup_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_desc',
            field=models.TextField(default='description', max_length=1000),
        ),
    ]
