# Generated by Django 4.0.3 on 2022-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_startup_startup_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='iitian',
            field=models.BooleanField(),
        ),
    ]
