# Generated by Django 4.0.3 on 2022-04-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_startup_iitian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_sector',
            field=models.CharField(default='FMCG', max_length=30),
        ),
    ]
