# Generated by Django 4.0.3 on 2022-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_startup_startup_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='hostel',
            field=models.CharField(choices=[('1', 'HOSTEL 1'), ('2', 'HOSTEL 2'), ('3', 'HOSTEL 3'), ('4', 'HOSTEL 4'), ('5', 'HOSTEL 5'), ('6', 'HOSTEL 6'), ('7', 'HOSTEL 7'), ('8', 'HOSTEL 8'), ('9', 'HOSTEL 9'), ('10', 'HOSTEL 10'), ('11', 'HOSTEL 11'), ('12', 'HOSTEL 12'), ('13', 'HOSTEL 13'), ('14', 'HOSTEL 14'), ('15', 'HOSTEL 15'), ('16', 'HOSTEL 16'), ('17', 'HOSTEL 17'), ('18', 'HOSTEL 18')], max_length=10),
        ),
    ]
