# Generated by Django 4.0.3 on 2022-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_startup_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='iitian',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_sector',
            field=models.CharField(choices=[('1', 'FMCG'), ('2', 'FINTECH'), ('3', 'EDTECH'), ('4', 'CONSULTING'), ('5', 'IT'), ('6', 'ECOMMERCE'), ('7', 'FOODTECH'), ('8', 'HARDWARE')], max_length=30, null=True),
        ),
    ]
